version: "3"
services:
    postgres:
        image: "postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=imunizeme
        ports:
            - "5432:5432"
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
    prest:
        build: .
        links:
            - "postgres:postgres"
        depends_on:
            - postgres
        environment:
            - IMUNIZEME_PG_HOST=postgres
            - IMUNIZEME_PG_USER=postgres
            - IMUNIZEME_PG_DBNAME=imunizeme
            - IMUNIZEME_PG_PORT=5432
            - IMUNIZEME_JWT_KEY=51d7fe292d4883dd6e408542denver
            - IMUNIZEME_PREST_PORT=3000
            - IMUNIZEME_PREST_HOST=0.0.0.0
            - IMUNIZEME_DEBUG=true
            - IMUNIZEME_CORS=*
            - IMUNIZEME_PREST_MIGRATIONS=./migrations
            - IMUNIZEME_PREST_QUERIES=./queries
        ports:
            - "3000:3000"